apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: java-test
spec:
  type: LoadBalancer
  selector:
    app: java-test
  ports:
  - name: http
    port: 80
    targetPort: 8080
    