apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: java-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-test
  template:
    metadata:
      labels:
        app: java-test
    spec:
      serviceAccount: udef-pod-reader
      containers:
      - name: server
        image: pvs5/java-test:1.2
        imagePullPolicy: Always        
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        #- name: JAVA_TOOL_OPTIONS
        #  value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y       
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
